apiVersion: v1
kind: Service
metadata:
  name: review-processor-service
  namespace: ns-review-processor-service
  labels:
    app: review-processor-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: review-processor-service